server:
  port: 9000
spring:
  application:
    name: gateway

spring:
  cloud:
    gateway:
      routes:
      - id: login
        uri: http://localhost:9090/
        predicates:
          - Path=/*/login/**
      - id: accounts
        uri: http://localhost:9091/
          - Path=/*/accounts/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true