spring:
  application:
    name: accountscards

  profiles:
    active: DEV

  datasource:
    url: jdbc:sqlserver://10.0.1.30:1433;databaseName=customers-spring;encrypt=true;trustServerCertificate=true
    username: sa
    password: 32bclp47
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  redis:
    database: 0
    host: 10.0.1.30
    port: 6379
    password: ""
    timeout: 60000

server:
  port: 9091

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      cards:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10s